### ISSUE TITLE
Add cargo stylus version to the name of created docker image

### ISSUE THREAD

**Issue by rimrakhimov** [OffchainLabs/cargo-stylus#88]
Currently created docker image name includes only the version of the rust toolchain and does not include the version of the cargo stylus package (`CARGO_PKG_VERSION`) - https://github.com/OffchainLabs/cargo-stylus/blob/main/check/src/docker.rs#L44-L47

That may result in the following scenario when next versions of the cargo stylus are released:
1. A user has used `cargo stylus 0.4.2` with rust-toolchain 1.80.0, deployed some contracts via that setup and has `cargo-stylus-1.80.0` image installed locally.
2. The user updates cargo stylus to v0.5.0
3. Deploys a new contract with new `v0.5.0` version. The code then just checks if `cargo-stylus-1.80.0` image exists locally (https://github.com/OffchainLabs/cargo-stylus/blob/main/check/src/docker.rs#L45) and as it already does, it uses that image that internally has `cargo stylus 0.4.2` installed.
4. When trying to verify the contract, the user believes that v0.5.0 version was used, while in reality it was v0.4.2

### Solution
I suggest to add a current cargo stylus version in the docker image name as well - e.g. `cargo-stylus-0.4.2-1.80.0`

**Comment by rauljordan** [comment]
hi @rimrakhimov thanks - I was able to reproduce. The issue was in the Rust code that detected the correct image was there. That code was not updated to support the correct version in name + toolchain, and we have fixed in #91 if you wish to try it out by removing cargo-stylus and doing `cargo install --path main` from source. Then, step (5) will be different and build the new image
